spring.application.name=Zent

#informacion general
spring.datasource.url=jdbc:h2:mem:zent_db
spring.datasource.username=sa
spring.datasource.password=

#base de datos virtual h2
spring.h2.console.enabled=true
spring.h2.console.path= /h2-console

#activacion del JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

